{{ if .Values.CREATE_NEW_IMAGE_STREAM }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: dev
  labels:
    app: {{ default .Release.Name .Values.NAME_OVERRIDE }}
  name: repo
  namespace: dev
spec:
  lookupPolicy:
    local: true
{{ end }}