apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Release.Name .Values.NAME_OVERRIDE }}
  labels: 
    app: {{ default .Release.Name .Values.NAME_OVERRIDE }}
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: {{ default .Release.Name .Values.NAME_OVERRIDE }}
  template:
    metadata:
      name: {{ default .Release.Name .Values.NAME_OVERRIDE }}
      labels:
        app: {{ default .Release.Name .Values.NAME_OVERRIDE }}
    spec:
      containers:
      - name: {{ default .Release.Name .Values.NAME_OVERRIDE }}
        image: "repo:{{ .Values.SRC_IMAGE_NAME }}"
        ports:
        - containerPort: 8080
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/"
            port: 8080
        resources:
          limits:
            memory: {{ .Values.MEMORY_LIMIT }}
        env: []