apiVersion: v1
kind: Service
metadata:
  name: {{ default .Release.Name .Values.NAME_OVERRIDE }}
  labels:
    app: {{ default .Release.Name .Values.NAME_OVERRIDE }}
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: {{ default .Release.Name .Values.NAME_OVERRIDE }}
